# Generated by Django 2.2.1 on 2019-05-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Clase', models.CharField(max_length=50)),
                ('Deck', models.CharField(max_length=5)),
                ('NoblePhantasm', models.CharField(max_length=50)),
            ],
        ),
    ]
